# This is a basic workflow to help you get started with Actions

name: Extractor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        commit_ind: [3]#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout RefactoringMiner
      uses: actions/checkout@v2
      with:
        repository: amir9979/RefactoringMiner
        path: .
        fetch-depth: 0
        ref: main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Build with Gradle
      run: ./gradlew.bat distZip
    

    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
    
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython

    - name: unzip
      shell: python
      run: |
            import zipfile
            with zipfile.ZipFile(r"build\distributions\RefactoringMiner-2.0.3.zip","r") as zip_ref:
              zip_ref.extractall("target")
            import git
            repo = git.repo('my-tools')
            commits = list(repo.iter_commits())
            ind = int(${{matrix.commit_ind}})
            start = commits[ind*1000]
            end = commits[(ind+1)*1000]
            print(start, end)
            

#     - name: execute
#       run: target\RefactoringMiner-2.0.2\bin\RefactoringMiner.bat -a my-tools master > out.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{github.event.issue.number}}.json
        # A file, directory or wildcard pattern that describes what to upload
        path: out.json


    - name: Close Issue
      continue-on-error: true
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
