# This is a basic workflow to help you get started with Actions

name: Extractor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout RefactoringMiner
      uses: actions/checkout@v2
      with:
        repository: amir9979/RefactoringMiner
        path: .
        fetch-depth: 0
        ref: main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Build with Gradle
      run: ./gradlew.bat distZip
    
    - name: ls
      run: ls -R
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: jar
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/jasome.jar

    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
    
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools
    
    - name: ls
      run: ls -R
    
    - name: unzip
      shell: python
      run: |
            import zipfile
            with zipfile.ZipFile(r"build\distributions\RefactoringMiner-2.0.2.zip","r") as zip_ref:
              zip_ref.extractall("target")

         
    - name: ls
      run: ls -R

    - name: execute
      run: target\bin\RefactoringMiner.bat -bc my-tools 273b353bf004e4c6108de3e97c327b9ec418d20f 286ab7c6dd4c4aae0b0290517ea3508487 > out.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{github.event.issue.number}}.json
        # A file, directory or wildcard pattern that describes what to upload
        path: out.json


    - name: Close Issue
      continue-on-error: true
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
